import _ from 'lodash'

const generateDeckName = () => {
  const adjectives = [
    'capricious',
    'selective',
    'four',
    'sudden',
    'unusual',
    'safe',
    'zesty',
    'efficient',
    'faulty',
    'ripe',
    'useless',
    'alive',
    'teeny-tiny',
    'like',
    'truculent',
    'lackadaisical',
    'long',
    'juvenile',
    'uppity',
    'adaptable',
    'damp',
    'fuzzy',
    'festive',
    'sad',
    'kindly',
    'beneficial',
    'observant',
    'dusty',
    'tense',
    'roomy',
    'tidy',
    'tall',
    'mean',
    'physical',
    'ugly',
    'bumpy',
    'bizarre',
    'gruesome',
    'fretful',
    'classy',
    'encouraging',
    'miniature',
    'silent',
    'halting',
    'gratis',
    'perfect',
    'messy',
    'square',
    'greasy',
    'awful',
    'delirious',
    'momentous',
    'peaceful',
    'coherent',
    'nimble',
    'tasteful',
    'obscene',
    'open',
    'wide-eyed',
    'assorted',
    'little',
    'dull',
    'ignorant',
    'invincible',
    'jazzy',
    'energetic',
    'lean',
    'true',
    'crabby',
    'learned',
    'low',
    'five',
    'incompetent',
    'past',
    'excited',
    'common',
    'therapeutic',
    'zealous',
    'valuable',
    'smelly',
    'romantic',
    'ill-fated',
    'combative',
    'obese',
    'skillful',
    'mindless',
    'available',
    'selfish',
    'minor',
    'excellent',
    'draconian',
    'slow',
    'motionless',
    'nonchalant',
    'illegal',
    'tested',
    'hard',
    'tremendous',
    'even',
  ] 

  const nouns = [
    'Legion', 'Brigade', 'Force', 'Squad', 'Company',
    'Warriors', 'Guard', 'Vanguard', 'Knights', 'Sentinels',
    'Defenders', 'Alliance', 'Battalion', 'Division', 'Corps',
    'Agony',
    'Ashtray',
    'Bear',
    'Digit',
    'Hold',
    'Jeep',
    'Naturalisation',
    'Property',
    'Subprime',
    'Vault',
    'Analyst',
    'Driveway',
    'Guest',
    'Icing',
    'Opponent',
    'Pith',
    'Prestige',
    'Proponent',
    'Rap',
    'Barbiturate',
    'Citizen',
    'Doll',
    'Fraction',
    'Freak',
    'Powder',
    'Rebel',
    'Stand',
    'Temperature',
    'Toothpick'
  ]

  const randomAdjective = _.capitalize(adjectives[Math.floor(Math.random() * adjectives.length)])
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)]

  return `${randomAdjective} ${randomNoun}`
}

export default generateDeckName